### PR TITLE
add version alias

### PR DESCRIPTION
**Pull request by spdegabrielle**
I think this is all that is required to fix 

https://github.com/Metaxal/quickscript-extra/issues/23

### CODE REVIEW

**Comment by countvajhula** [comment]
Probably needs these imports:
```
(require version-case
         mischief/shorthand) ; for define-alias
```

**Comment by spdegabrielle** [comment]
> Probably needs these imports:
> 
> ```
> (require version-case
>          mischief/shorthand) ; for define-alias
> ```

Thank you

**Comment by Metaxal** [comment]
Thanks for the patch @spdegabrielle 
Unfortunately I cannot make the small package `search-list-box` depend on the large and varied `mischief` (it also has failures on the pkg server). It doesn't even have a license as far as I can tell. Any other way around this issue?

**Comment by Metaxal** [comment]
In the end I simply reverted to merely `define-simple-macro` with  11103aa , which should fix this. I'm closing this issue

**Comment by countvajhula** [comment]
The main interface that does this seems to be `make-rename-transformer`. For instance, another implementation of [define-alias](https://docs.racket-lang.org/adjutor/Stable.html#%28form._%28%28lib._adjutor%2Fmain..rkt%29._define-alias%29%29) in the adjutor library is just a thin wrapper around it. So you could alternatively use that / write the implementation in a local utils file if you prefer.

But of course `define-simple-macro` works as well!

**Pull request closed without merging**
